[project]
name = "mlops-zoomcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
    "evidently==0.6.7",
    "hyperopt>=0.2.7",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.3",
    "mlflow>=3.1.1",
    "nb-clean>=4.0.1",
    "pandas>=2.3.0",
    "prefect>=1.4.1",
    "psycopg2>=2.9.10",
    "pyarrow>=20.0.0",
    "scikit-learn>=1.7.0",
    "scipy>=1.15.3",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.41",
    "tqdm>=4.67.1",
]
